# .gitlab-ci.yml
# CI/CD Pipeline stages run sequentially unless dependencies (needs) are defined
stages:
  - test
  - build
  - deploy

variables:
  SECRET_DETECTION_ENABLED: 'true'

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

# ------------------ Backend Testing ------------------
test:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - backend/
  image: python:3.11-slim
  before_script:
    - cd backend/test
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest pytest-asyncio httpx asgi-lifespan
  script:
    - pytest test_main.py --maxfail=1 --disable-warnings -v


# ------------------ Docker Build ------------------
build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  image: google/cloud-sdk:slim
  script:
    - echo "Building Docker image"
    - gcloud builds submit --tag gcr.io/$GOOGLE_PROJECT_ID/$GOOGLE_CLOUD_BUILD

# ------------------ Deploy to Cloud Run ------------------
deploy:
  stage: deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  image: google/cloud-sdk:slim 
  script:
    - echo "Deploying to Cloud Run"
    - gcloud run deploy $GOOGLE_CLOUD_BUILD \
        --image gcr.io/$GOOGLE_PROJECT_ID/$GOOGLE_CLOUD_BUILD \
        --region 'us-central1' \
        --port 80 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars "VITE_API_URL=$API_URL"
# Notes:
# 1. Sensitive variables (API keys, secrets) should be configured via GitLab UI (Settings > CI/CD > Variables) NOT in this file.
# 2. You can customize SAST, Dependency Scanning, etc. via GitLab’s official templates.
# 3. Secret Detection template is included here to prevent accidental commit of secrets.