version: '1.0'

services:
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    variable:
      - GEMINI_API_KEY=${GEMINI_KEY}
      - MONGO_URI=${MONGO_URI}
    # depends_on:
    #   - mongo

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     environment:
#       - MONGO_URI=${MONGO_URI}
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data: